
export const GET_INFO1_REQUEST = "GET_INFO1_REQUEST";
export const GET_INFO1_SUCCESS = "GET_INFO1_SUCCESS";
export const GET_INFO1_FAILURE = "GET_INFO1_FAILURE";

export const GET_INFO2_REQUEST = "GET_INFO2_REQUEST";
export const GET_INFO2_SUCCESS = "GET_INFO2_SUCCESS";
export const GET_INFO2_FAILURE = "GET_INFO2_FAILURE";

export const GET_CHARTDATA_REQUEST = "GET_CHARTDATA_REQUEST";
export const GET_CHARTDATA_SUCCESS = "GET_CHARTDATA_SUCCESS";
export const GET_CHARTDATA_FAILURE = "GET_CHARTDATA_FAILURE";

export const GET_TABLEDATA_REQUEST = "GET_TABLEDATA_REQUEST";
export const GET_TABLEDATA_SUCCESS = "GET_TABLEDATA_SUCCESS";
export const GET_TABLEDATA_FAILURE = "GET_TABLEDATA_FAILURE";

export const CATCH_DATEPCIKER_DATA = "CATCH_DATEPCIKER_DATA";
export const CATCH_RADIOBOX_DATA = "CATCH_RADIOBOX_DATA";
export const THROW_FILTER_DATA = "THROW_FILTER_DATA";
export const GET_FILTER_DATA = "GET_FILTER_DATA";

export const GET_TESTDATA_REQUEST = "GET_TESTDATA_REQUEST";
export const GET_TESTDATA_SUCCESS = "GET_TESTDATA_SUCCESS";
export const GET_TESTDATA_FAILURE = "GET_TESTDATA_FAILURE";
